services:
  nginx:
    build:
      context: requirements/nginx/.
      args:
        SERVER_NAME: ${SERVER_NAME}
    image: nginx
    container_name: nginx
    depends_on:
      mariadb:
        condition: service_started
      wordpress:
        condition: service_started
    ports:
      - "443:443"
    volumes:
      - /home/jazevedo/data/wordpress:/var/www/html
      - ./requirements/nginx/conf:/etc/nginx/conf.d:ro
    environment:
      - SERVER_NAME=${SERVER_NAME}
    networks:
      - inception
    restart: always

  wordpress:
    build: requirements/wordpress/.
    image: wordpress
    container_name: wp-php
    depends_on:
      mariadb:
        condition: service_started
    volumes:
      - wordpress_data:/var/www/html
      - ../secrets:/run/secrets:ro
    environment:
      - SERVER_NAME=${SERVER_NAME}
      - WP_URL=${WP_URL}
      - WP_TITLE=${WP_TITLE}
      - DB_HOST=${DB_HOST}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD_FILE=/run/secrets/wp_db_password.txt
      - WP_ADMIN_USER=${WP_ADMIN_USER}
      - WP_ADMIN_PASSWORD_FILE=/run/secrets/wp_admin_password.txt
      - WP_ADMIN_EMAIL=${WP_ADMIN_EMAIL}
      - WP_USER2=${WP_USER2}
      - WP_USER2_PASSWORD_FILE=/run/secrets/wp_user2_password.txt
      - WP_USER2_EMAIL=${WP_USER2_EMAIL}
      - WP_USER2_ROLE=${WP_USER2_ROLE}
    networks:
      - inception
    restart: always

  mariadb:
    build: requirements/mariadb/.
    image: mariadb
    container_name: mariadb
    volumes:
      - mariadb_data:/var/lib/mysql
      - ../secrets:/run/secrets:ro
    environment:
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD_FILE=/run/secrets/wp_db_password.txt
      - MYSQL_ROOT_PASSWORD_FILE=/run/secrets/db_root_password.txt
    networks:
      - inception
    restart: always

networks:
  inception:

volumes:
  wordpress_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/jazevedo/data/wordpress

  mariadb_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/jazevedo/data/mariadb
